## Telco-vecchio agent configuration file

# [[user]] items define the users allowed to interact with telco-vecchio
# for each item, `name`, `phone_number` and `email` fields are mandatory

#[[user]]
#name = "..."
#phone_number = "+..."
#email = "..."

# [[application]] items define the applications to be tunneled through telco-vecchio
# for each item, `name`, `host_ip` and `port` fields are mandatory

#[[application]]
#name = "..."
#host_ip = "..."
#port = ...

#
# Technical configuration
#

[sms_config]
modem_device = "/dev/ttyUSB2"
qmi_modem_device = "/dev/cdc-wdm0"
qmi_binary_file = "uqmi"
sim_pin = ...
sms_send_timeout_sec = 5

[email_config]
binary_file = "sendmail"
sender_alias = "Telco-Vecchio"
server_domain = ...
internet_host = "8.8.8.8"

[ssh_config]
binary_file = "ssh"
key_file = "/etc/dropbear/dropbear_rsa_host_key"
service_user = "v2"
service_host = "connect.ngrok-agent.com"
tunnel_input_port = 0
tunnel_setup_timeout_sec = 5

[init_config]
init_status_refresh_period_seconds = 10
init_status_refresh_max_retry = 10

